### ISSUE TITLE
Multiple tile source bounding box

### ISSUE THREAD

**Issue by cedricguignard** [mapbox/DEPRECATED-mapbox-ios-sdk#168]
Not sure about the expected behavior but it seems that when we add tile source in RMTileSourceContainer the new bounding box is an intersect of all source's bounding boxes but it should be a union right ?

I changed

```
_latitudeLongitudeBoundingBox = ((RMSphericalTrapezium) {
    .northEast = {
        .latitude = MIN(_latitudeLongitudeBoundingBox.northEast.latitude, newLatitudeLongitudeBoundingBox.northEast.latitude),
        .longitude = MIN(_latitudeLongitudeBoundingBox.northEast.longitude, newLatitudeLongitudeBoundingBox.northEast.longitude)},
    .southWest = {
        .latitude = MAX(_latitudeLongitudeBoundingBox.southWest.latitude, newLatitudeLongitudeBoundingBox.southWest.latitude),
        .longitude = MAX(_latitudeLongitudeBoundingBox.southWest.longitude, newLatitudeLongitudeBoundingBox.southWest.longitude)
    }
});
```

to

```
_latitudeLongitudeBoundingBox = ((RMSphericalTrapezium) {
    .northEast = {
        .latitude = MAX(_latitudeLongitudeBoundingBox.northEast.latitude, newLatitudeLongitudeBoundingBox.northEast.latitude),
        .longitude = MAX(_latitudeLongitudeBoundingBox.northEast.longitude, newLatitudeLongitudeBoundingBox.northEast.longitude)},
    .southWest = {
        .latitude = MIN(_latitudeLongitudeBoundingBox.southWest.latitude, newLatitudeLongitudeBoundingBox.southWest.latitude),
        .longitude = MIN(_latitudeLongitudeBoundingBox.southWest.longitude, newLatitudeLongitudeBoundingBox.southWest.longitude)
    }
});
```

and it works perfectly fine for me.

**Comment by incanus** [comment]
I'll take a look at this. I'm unsure of the original intended behavior as this came from the upstream project, but on the surface, your fix sounds right.

**Comment by incanus** [comment]
Is this fixed in 1.0.0? I know a change came down from upstream related to this.

**Comment by cedricguignard** [comment]
Sorry I don't think I'm gonna update mapbox in this project yet.

**Comment by incanus** [comment]
Ok. The change you want is probably this one; you might be able to just patch it into your version. 

https://github.com/Alpstein/route-me/commit/0785ddbd7f9e57f864bcd78e76f9bd0d2da2fd9d

**Comment by incanus** [comment]
I'll close here for now. Feel free to reopen if this reoccurs in the current version.

**Comment by mgraesser** [comment]
FYI - 1.0 did not fix the problem described by Cedric, Multiple tile source bounding box. I did add Cedric changes in but found it needed a little check when you do not have more then one tile source. So I modified addTileSources with Cedric's changes but use the old min max if there is only one tileSource. 

```
if ([_tileSources count] > 0) {
    // a union
    _latitudeLongitudeBoundingBox = ((RMSphericalTrapezium) {
        .northEast = {
            .latitude = MAX(_latitudeLongitudeBoundingBox.northEast.latitude, newLatitudeLongitudeBoundingBox.northEast.latitude),
            .longitude = MAX(_latitudeLongitudeBoundingBox.northEast.longitude, newLatitudeLongitudeBoundingBox.northEast.longitude)},
        .southWest = {
            .latitude = MIN(_latitudeLongitudeBoundingBox.southWest.latitude, newLatitudeLongitudeBoundingBox.southWest.latitude),
            .longitude = MIN(_latitudeLongitudeBoundingBox.southWest.longitude, newLatitudeLongitudeBoundingBox.southWest.longitude)
        }
    });
}
else {
   _latitudeLongitudeBoundingBox = ((RMSphericalTrapezium) {
        .northEast = {
            .latitude = MIN(_latitudeLongitudeBoundingBox.northEast.latitude, newLatitudeLongitudeBoundingBox.northEast.latitude),
            .longitude = MIN(_latitudeLongitudeBoundingBox.northEast.longitude, newLatitudeLongitudeBoundingBox.northEast.longitude)},
        .southWest = {
            .latitude = MAX(_latitudeLongitudeBoundingBox.southWest.latitude, newLatitudeLongitudeBoundingBox.southWest.latitude),
            .longitude = MAX(_latitudeLongitudeBoundingBox.southWest.longitude, newLatitudeLongitudeBoundingBox.southWest.longitude)
        }
    });

}
```

**Comment by namannik** [comment]
This is still an issue for my use case, which is an `RMMapView` with multiple `RMMBTileSources` covering different regions.  Swapping the max and min solves the problem, but it's a change I need to make each time I update the MapBox library.

Making this change has a side effect, though.  Because of the way TileMill creates tiles, edge tiles are rendered beyond the bounding box.  This is especially noticeable at lower zoom levels, and results in the edges of the map seeming to disappear as the user zooms in.  My solution has been to apply a mask to edge tiles, effectively cropping them to the bounding box.  I've added this code in `RMMapTiledLayerView.m` in [my fork](https://github.com/namannik/mapbox-ios-sdk).
